---
name: Net-SPDY
version: 0.1_2
author:
  - 'Lubomir Rintel <lkundrak@v3.sk>'
abstract: SPDY protocol implementation
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Net-SPDY
  license: http://dev.perl.org/licenses/
  repository: https://github.com/lkundrak/net-spdy
build_requires:
  Test::Pod: 0
requires:
  Compress::Zlib: 0
  IO::Socket::SSL: 0
  URI: 0
configure_requires:
  Module::Build: 0.35
provides:
  Net::SPDY::Compressor:
    file: lib/Net/SPDY/Compressor.pm
    version: 0.1
  Net::SPDY::Framer:
    file: lib/Net/SPDY/Framer.pm
    version: 0.1
  Net::SPDY::Session:
    file: lib/Net/SPDY/Session.pm
    version: 0.1
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
